### PR TITLE
11/7 Updates

### PR DESCRIPTION
**Pull request by Araceli-J**
questions are left in the html file

### CODE REVIEW

**Review by axanthus — COMMENTED** [review]
Your progress looks great! To answer your questions that you put in comments of your html:
- Section from Created Jun 4, 2014 to top 3%: What are you confused about? Are you not sure which html elements to use, or do you not understand the content?
- "Can the figures just be a ul...?": So what you referred to as a figure in your annotated screenshot should be a list of buttons. However buttons don't work well with a ul tag, so you can use a div with a set of buttons inside.
- Eventually the comment section will be brought in via api, but you can add mock data with html to make it look real for now. Remember only single top-level comments, no subcomments.

**Comment by Araceli-J** [comment]
For the first one, I am not sure of which html elements to use. I am confused on the set up of it because everything is stacked on top of each other so I am confused on the html elements to use for that section.

What can be used instead of the ul tag? The word doesn't show up in the comments. Will the buttons also have images in it and do the buttons have to function or can they just be buttons that can be clicked? @axanthus 
Also do the drop downs have to work, or is the only working functionality on the page be the comment section? I am just wondering if my page has to look exactly like the reddit page exactly section by section.

**Comment by Araceli-J** [comment]
article won't center in the page

**Comment by axanthus** [comment]
In response to your questions, for the first one, div and p tags will work. You just need a way to organize content, so divs are fine and you can flex them as needed.

2. I meant to say divs
3. You don't need the dropdowns working yet, you'll use JS for those

**Pull request merged**
