### PR TITLE
Araceli's branch

### PR DESCRIPTION
**Pull request by Araceli-J**
for week5 assignment

### CODE REVIEW

**Review by axanthus — APPROVED** [review]
Looks good, make sure to avoid using <div> where possible and use semantic html tags.

**Comment by axanthus** [comment]
You can merge this now.

**Comment by Araceli-J** [comment]
What do I avoid using and use in replacement html tags? The word after avoid using is missing @axanthus

**Comment by axanthus** [comment]
Sorry, I meant to say "div"

**Pull request merged**
